### PR TITLE
[ChopBox] [#101409884] Feature/multiple images upload"

### PR DESCRIPTION
**Pull request by kola-er**
This is the new branch

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Some of your commit messages are `Uncompleted test` ,`Newly created`, `Update done by the system`, `Include for testing`. why? These are terrible commit messages. It doesn't really reflect what you did from a distance!

**Comment by kola-er** [comment]
Those were part of the mistakes I was making before you corrected me. I have learnt my lessons.

**Comment by unicodeveloper** [comment]
I need you to amend those commit messages to something more appropriate!

**Comment by unicodeveloper** [comment]
You can easily ammend them. check this out 
screen shot 2015-09-07 at 6 07 17 pm if you don't know how to go about it

**Pull request closed without merging**
