### PR TITLE
[ChopBox] [#102129456] Feature/design of about and terms pages

### PR DESCRIPTION
**Pull request by kola-er**

### CODE REVIEW

**Comment by andela-potemuyiwa** [comment]
Why do you have all these old commits together with the new ones here ?

**Comment by unicodeveloper** [comment]
Squash all these commits into the necessary ones for this feature. I don't want to see old commits that have nothing to do with this feature here! :angry:

**Comment by kola-er** [comment]
I've squashed all the recent commits into one.

**Comment by unicodeveloper** [comment]
@andela-kerinoso You have still not taken care of this

**Pull request closed without merging**
