### PR TITLE
[Chopbox][#108088330] Save avatar from social platform

### PR DESCRIPTION
**Pull request by kola-er**

### CODE REVIEW

**Comment by unicodeveloper** [comment]
@andela-kerinoso did you ensure that the nitpick issue was fixed before merging?

**Comment by kola-er** [comment]
Oh! I didn't notice it. I will be observant on subsequent ones.

**Comment by unicodeveloper** [comment]
Alright. You should be very observant. Attention to details is paramount. @andela-kerinoso

**Comment by kola-er** [comment]
Yes, it is. Thanks for the notification.

**Pull request merged**
